#include "services/idle.hpp"

#include "services/config.hpp"
#include "services/gamepad.hpp"
#include "services/hyprland.hpp"
#include "services/session.hpp"

#include <gdk/wayland/gdkwayland.h>
#include <gdkmm.h>
#include <wayland-client.h>

#include "ext-idle-notify-v1-client-protocol.h" // generated by wayland-scanner (meson)
#include "idle-inhibit-unstable-v1-client-protocol.h"

#include <algorithm>
#include <cstring>

namespace hyprshell {

namespace {

// Noctalia's lockAndSuspend waits (up to 3s) for its lock screen to confirm
// the lock before suspending.
constexpr unsigned kLockBeforeSuspendTimeoutMs = 3000;
constexpr unsigned kOverlayCleanupMs = 500; // Noctalia's overlayCleanupTimer
// How long a controller event keeps the idle inhibitor: the compositor
// restarts every idle timeout when it is released.
constexpr unsigned kExternalActivityHoldMs = 3000;

} // namespace

struct Idle::Monitor {
    ext_idle_notification_v1* notification = nullptr;
    int timeout_s = 0;
    std::function<void()> on_idled;
    std::function<void()> on_resumed;

    ~Monitor() {
        if (notification)
            ext_idle_notification_v1_destroy(notification);
    }
};

Idle& Idle::get() {
    static Idle instance;
    return instance;
}

Idle::Idle() {
    dry_run_ = g_getenv("HS_IDLE_DRY_RUN") != nullptr;
    if (dry_run_)
        g_message("idle: dry run — actions are logged, not executed");

    auto display = Gdk::Display::get_default();
    if (!display || !GDK_IS_WAYLAND_DISPLAY(display->gobj())) {
        g_warning("idle: no Wayland display — idle actions disabled");
        return;
    }
    wl_display* wl = gdk_wayland_display_get_wl_display(display->gobj());
    if (auto seat = display->get_default_seat())
        seat_ = gdk_wayland_seat_get_wl_seat(seat->gobj());
    if (!seat_) {
        g_warning("idle: no seat — idle actions disabled");
        return;
    }

    // Bind the notifier global. The roundtrip pumps GDK's own queue (the
    // same thing gtk4-layer-shell does at init) so the globals are known here.
    registry_ = wl_display_get_registry(wl);
    static const wl_registry_listener kRegistryListener = {on_global, on_global_remove};
    wl_registry_add_listener(registry_, &kRegistryListener, this);
    wl_display_roundtrip(wl);
    if (!notifier_) {
        g_message("idle: compositor lacks ext-idle-notify-v1 — idle actions disabled");
        return;
    }

    Config::get().signal_changed().connect(sigc::mem_fun(*this, &Idle::apply_config));
    apply_config();

    if (inhibit_manager_ && compositor_)
        Gamepad::get().signal_activity().connect(
            sigc::mem_fun(*this, &Idle::report_external_activity));
    else
        g_message("idle: compositor lacks idle-inhibit-v1 — controller input cannot reset idleness");
}

const char* Idle::stage_name(Stage stage) {
    switch (stage) {
    case Stage::ScreenOff:
        return "screen off";
    case Stage::Lock:
        return "lock";
    case Stage::Suspend:
        return "suspend";
    case Stage::None:
        break;
    }
    return "none";
}

Idle::Stage Idle::stage_from_key(const std::string& key) {
    if (key == "screen_off")
        return Stage::ScreenOff;
    if (key == "lock")
        return Stage::Lock;
    if (key == "suspend")
        return Stage::Suspend;
    return Stage::None;
}

// -- wayland callbacks (dispatched by GDK on the main loop) ---------------------

void Idle::on_global(void* data, wl_registry* registry, uint32_t name, const char* interface,
                     uint32_t version) {
    auto* self = static_cast<Idle*>(data);
    if (!self->notifier_ && std::strcmp(interface, ext_idle_notifier_v1_interface.name) == 0) {
        // v1 notifications respect idle inhibitors (v2's input variant would not)
        self->notifier_ = static_cast<ext_idle_notifier_v1*>(wl_registry_bind(
            registry, name, &ext_idle_notifier_v1_interface, std::min<uint32_t>(version, 1)));
    } else if (!self->inhibit_manager_ &&
               std::strcmp(interface, zwp_idle_inhibit_manager_v1_interface.name) == 0) {
        self->inhibit_manager_ = static_cast<zwp_idle_inhibit_manager_v1*>(wl_registry_bind(
            registry, name, &zwp_idle_inhibit_manager_v1_interface, 1));
    } else if (!self->compositor_ && std::strcmp(interface, wl_compositor_interface.name) == 0) {
        self->compositor_ = static_cast<wl_compositor*>(
            wl_registry_bind(registry, name, &wl_compositor_interface, std::min<uint32_t>(version, 4)));
    }
}

void Idle::on_global_remove(void*, wl_registry*, uint32_t) {}

void Idle::on_monitor_idled(void* data, ext_idle_notification_v1*) {
    auto* monitor = static_cast<Monitor*>(data);
    if (monitor->on_idled)
        monitor->on_idled();
}

void Idle::on_monitor_resumed(void* data, ext_idle_notification_v1*) {
    auto* monitor = static_cast<Monitor*>(data);
    if (monitor->on_resumed)
        monitor->on_resumed();
}

std::unique_ptr<Idle::Monitor> Idle::make_monitor(int timeout_s, std::function<void()> on_idled,
                                                  std::function<void()> on_resumed) {
    auto monitor = std::make_unique<Monitor>();
    monitor->timeout_s = timeout_s;
    monitor->on_idled = std::move(on_idled);
    monitor->on_resumed = std::move(on_resumed);
    monitor->notification = ext_idle_notifier_v1_get_idle_notification(
        notifier_, static_cast<uint32_t>(timeout_s) * 1000u, seat_);
    static const ext_idle_notification_v1_listener kListener = {on_monitor_idled,
                                                                 on_monitor_resumed};
    ext_idle_notification_v1_add_listener(monitor->notification, &kListener, monitor.get());
    return monitor;
}

// -- config -------------------------------------------------------------------

void Idle::apply_config() {
    const auto& cfg = Config::get().idle();
    set_monitor(screen_off_, Stage::ScreenOff, cfg.enabled ? cfg.screen_off_timeout : 0);
    set_monitor(lock_, Stage::Lock, cfg.enabled ? cfg.lock_timeout : 0);
    set_monitor(suspend_, Stage::Suspend, cfg.enabled ? cfg.suspend_timeout : 0);
    ensure_heartbeat();
    apply_custom_monitors();
}

void Idle::set_monitor(std::unique_ptr<Monitor>& slot, Stage stage, int timeout_s) {
    if (timeout_s <= 0) {
        if (slot) {
            slot.reset();
            g_message("idle: %s disabled", stage_name(stage));
        }
        return;
    }
    if (slot && slot->timeout_s == timeout_s)
        return;
    // the protocol has no update-timeout request — recreate the notification
    slot.reset();
    slot = make_monitor(
        timeout_s, [this, stage] { on_idle(stage); },
        [this, stage] {
            g_message("idle: activity — %s notification resumed (fade %s, screen off %d)",
                      stage_name(stage), stage_name(fade_pending_), screen_off_active_);
            cancel_fade();
        });
    g_message("idle: %s after %d s of inactivity", stage_name(stage), timeout_s);
}

void Idle::ensure_heartbeat() {
    if (heartbeat_)
        return;
    heartbeat_ = make_monitor(
        1,
        [this] {
            idle_seconds_ = 1;
            idle_counter_.disconnect();
            idle_counter_ = Glib::signal_timeout().connect(
                [this] {
                    ++idle_seconds_;
                    return true;
                },
                1000);
        },
        [this] { on_heartbeat_resumed(); });
}

// Noctalia's heartbeat resume: stop counting, fire the resume command of the
// stage whose fade was interrupted, cancel the fade.
void Idle::on_heartbeat_resumed() {
    g_message("idle: heartbeat resumed after %d s", idle_seconds_);
    idle_counter_.disconnect();
    idle_seconds_ = 0;
    const auto& cfg = Config::get().idle();
    if (fade_pending_ == Stage::Lock && !cfg.resume_lock_command.empty())
        run_command(cfg.resume_lock_command);
    else if (fade_pending_ == Stage::Suspend && !cfg.resume_suspend_command.empty())
        run_command(cfg.resume_suspend_command);
    cancel_fade();
    cleanup_timer_.disconnect();
}

void Idle::apply_custom_monitors() {
    custom_.clear();
    const auto& cfg = Config::get().idle();
    if (!cfg.enabled)
        return;
    for (const auto& entry : cfg.custom_commands) {
        if (entry.timeout <= 0 || (entry.command.empty() && entry.resume_command.empty()))
            continue;
        custom_.push_back(make_monitor(
            entry.timeout,
            [this, command = entry.command] {
                if (!command.empty())
                    run_command(command);
            },
            [this, command = entry.resume_command] {
                if (!command.empty())
                    run_command(command);
            }));
        g_message("idle: custom command after %d s", entry.timeout);
    }
}

// -- stages -------------------------------------------------------------------

bool Idle::stage_enabled(Stage stage) const {
    const auto& cfg = Config::get().idle();
    if (!cfg.enabled)
        return false;
    switch (stage) {
    case Stage::ScreenOff:
        return cfg.screen_off_timeout > 0;
    case Stage::Lock:
        return cfg.lock_timeout > 0;
    case Stage::Suspend:
        return cfg.suspend_timeout > 0;
    case Stage::None:
        break;
    }
    return false;
}

void Idle::on_idle(Stage stage) {
    g_message("idle: %s notification idled (fade %s, idle %d s)", stage_name(stage),
              stage_name(fade_pending_), idle_seconds_);
    if (stage == Stage::None || !stage_enabled(stage))
        return;
    if (fade_pending_ != Stage::None) {
        // a fade is running — queue this stage for after it completes
        if (stage != fade_pending_ &&
            std::find(queued_.begin(), queued_.end(), stage) == queued_.end())
            queued_.push_back(stage);
        return;
    }
    const int fade_s = Config::get().idle().fade_duration;
    g_message("idle: %s stage reached — fading out for %d s", stage_name(stage), fade_s);
    fade_pending_ = stage;
    fade_changed_.emit();
    grace_timer_.disconnect();
    grace_timer_ = Glib::signal_timeout().connect(
        [this] {
            execute_action(fade_pending_);
            cleanup_timer_.disconnect();
            cleanup_timer_ = Glib::signal_timeout().connect(
                [this] {
                    fade_pending_ = Stage::None;
                    fade_changed_.emit();
                    run_next_queued_stage();
                    return false;
                },
                kOverlayCleanupMs);
            return false;
        },
        static_cast<unsigned>(std::max(1, fade_s)) * 1000u);
}

void Idle::cancel_fade() {
    if (fade_pending_ == Stage::None) {
        queued_.clear();
        restore_monitors();
        return;
    }
    g_message("idle: fade cancelled (%s)", stage_name(fade_pending_));
    fade_pending_ = Stage::None;
    queued_.clear();
    grace_timer_.disconnect();
    cleanup_timer_.disconnect();
    fade_changed_.emit();
    restore_monitors();
}

void Idle::restore_monitors() {
    if (!screen_off_active_)
        return;
    screen_off_active_ = false;
    if (dry_run_)
        g_message("idle [dry run]: would turn the monitors back on");
    else
        Hyprland::get().set_dpms(true);
    const auto& cfg = Config::get().idle();
    if (!cfg.resume_screen_off_command.empty())
        run_command(cfg.resume_screen_off_command);
}

void Idle::execute_action(Stage stage) {
    const auto& cfg = Config::get().idle();
    g_message("idle: executing %s", stage_name(stage));
    switch (stage) {
    case Stage::ScreenOff:
        run_command(cfg.screen_off_command);
        if (dry_run_)
            g_message("idle [dry run]: would turn the monitors off");
        else
            Hyprland::get().set_dpms(false);
        screen_off_active_ = true;
        break;
    case Stage::Lock:
        run_command(cfg.lock_command);
        lock();
        break;
    case Stage::Suspend:
        run_command(cfg.suspend_command);
        if (cfg.lock_before_suspend && !dry_run_ && !session_locked()) {
            // suspend once the lock screen reports the lock, or after a
            // grace period if it never does (Noctalia's lockAndSuspend)
            lock();
            suspend_timer_.disconnect();
            locked_connection_.disconnect();
            locked_connection_ = signal_session_locked().connect([this](bool locked) {
                if (!locked)
                    return;
                locked_connection_.disconnect();
                suspend_timer_.disconnect();
                suspend();
            });
            suspend_timer_ = Glib::signal_timeout().connect(
                [this] {
                    locked_connection_.disconnect();
                    g_warning("idle: lock screen did not confirm the lock — suspending anyway");
                    suspend();
                    return false;
                },
                kLockBeforeSuspendTimeoutMs);
        } else {
            if (cfg.lock_before_suspend)
                lock();
            suspend();
        }
        break;
    case Stage::None:
        break;
    }
}

void Idle::run_next_queued_stage() {
    if (fade_pending_ != Stage::None)
        return;
    if (idle_seconds_ <= 0) {
        queued_.clear(); // the user is back — nothing else fires
        return;
    }
    while (!queued_.empty()) {
        const Stage next = queued_.front();
        queued_.erase(queued_.begin());
        if (!stage_enabled(next))
            continue;
        g_message("idle: running queued stage %s", stage_name(next));
        on_idle(next);
        return;
    }
}

void Idle::run_command(const std::string& command) {
    if (command.empty())
        return;
    if (dry_run_) {
        g_message("idle [dry run]: would run: %s", command.c_str());
        return;
    }
    spawn_detached({"sh", "-c", command});
}

void Idle::lock() {
    if (dry_run_) {
        g_message("idle [dry run]: would lock the session");
        return;
    }
    g_message("idle: requesting the session lock");
    request_lock(); // the shell's own lock screen (bar/lock_screen)
}

void Idle::suspend() {
    if (dry_run_) {
        g_message("idle [dry run]: would suspend");
        return;
    }
    spawn_detached({"sh", "-c", "systemctl suspend || loginctl suspend"});
}

// -- input the compositor cannot see -------------------------------------------

// The inhibitor sits on a bare wl_surface that never gets a role or a buffer.
// Hyprland attaches no desktop surface to such a surface and treats its
// inhibitor as a "non-desktop element, assumed visible" (IdleInhibitor.cpp),
// so it inhibits unconditionally — no window has to be mapped for it. While
// inhibited the compositor disarms our notifications (sending `resumed` if one
// had idled, which cancels a fade); destroying the inhibitor re-arms them with
// their full timeouts, i.e. the idle clock restarts.
void Idle::report_external_activity() {
    if (!inhibit_manager_ || !compositor_)
        return;
    if (!inhibit_surface_)
        inhibit_surface_ = wl_compositor_create_surface(compositor_);
    if (!inhibitor_) {
        inhibitor_ = zwp_idle_inhibit_manager_v1_create_inhibitor(inhibit_manager_, inhibit_surface_);
        g_debug("idle: external input — holding an idle inhibitor");
    }
    inhibit_release_.disconnect();
    inhibit_release_ = Glib::signal_timeout().connect(
        [this] {
            if (inhibitor_) {
                zwp_idle_inhibitor_v1_destroy(inhibitor_);
                inhibitor_ = nullptr;
                g_debug("idle: external input hold over — idle timers restart");
            }
            return false;
        },
        kExternalActivityHoldMs);
}

// -- dev hooks ------------------------------------------------------------------

void Idle::simulate_idled(Stage stage) {
    g_message("idle: simulating idle for %s", stage_name(stage));
    if (idle_seconds_ <= 0) {
        idle_seconds_ = 1; // as the heartbeat would have reported
        idle_counter_.disconnect();
        idle_counter_ = Glib::signal_timeout().connect(
            [this] {
                ++idle_seconds_;
                return true;
            },
            1000);
    }
    on_idle(stage);
}

void Idle::simulate_resumed() {
    g_message("idle: simulating resume");
    on_heartbeat_resumed();
}

} // namespace hyprshell
